/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface UIBezierPath : NSObject
{
    struct CGPath *_pathRef;
    float _width;
}

+ (id)bezierPath;	// IMP=0x323b9978
+ (id)bezierPathKnockingOutBottomOfRect:(struct CGRect)fp8 withCornerRadius:(float)fp24;	// IMP=0x323b9e48
+ (id)bezierPathKnockingOutTopOfRect:(struct CGRect)fp8 withCornerRadius:(float)fp24;	// IMP=0x323b9cb0
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedCorners:(int)fp24 visibleEdges:(int)fp28 cornerRadius:(float)fp32;	// IMP=0x323b9fb4
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedCorners:(int)fp24 withCornerRadii:(id)fp28;	// IMP=0x323ba590
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedCorners:(int)fp24 withCornerRadius:(float)fp28;	// IMP=0x323bab68
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedEdges:(int)fp24;	// IMP=0x323baed0
- (struct CGPath *)_pathRef;	// IMP=0x323b9a70
- (void)appendBezierPath:(id)fp8;	// IMP=0x323b9ab0
- (void)appendBezierPathWithArcWithCenter:(struct CGPoint)fp8 radius:(float)fp16 startAngle:(float)fp20 endAngle:(float)fp24 clockwise:(BOOL)fp28;	// IMP=0x323b9bb8
- (void)appendBezierPathWithOvalInRect:(struct CGRect)fp8;	// IMP=0x323b9b14
- (void)appendBezierPathWithOvalInRect:(struct CGRect)fp8 transform:(struct CGAffineTransform)fp24;	// IMP=0x323b9b5c
- (void)appendBezierPathWithRect:(struct CGRect)fp8;	// IMP=0x323b9acc
- (void)clip;	// IMP=0x323b9c88
- (void)closePath;	// IMP=0x323b9ba4
- (void)dealloc;	// IMP=0x323b9a1c
- (void)fill;	// IMP=0x323b9c0c
- (id)init;	// IMP=0x323b99c0
- (void)lineToPoint:(struct CGPoint)fp8;	// IMP=0x323b9a94
- (void)moveToPoint:(struct CGPoint)fp8;	// IMP=0x323b9a78
- (void)setLineWidth:(float)fp8;	// IMP=0x323b9c04
- (void)stroke;	// IMP=0x323b9c44

@end

