install:
	install -d -v architecture/arm /usr/include/architecture/arm
	install -d -v arm /usr/include/arm
	install -b -v fenv.h math.h TargetConditionals.h /usr/include
	install -b -v machine/*.h /usr/include/machine
	install -b -v mach/machine/*.h /usr/include/mach/machine
	install -b -v sys/cdefs.h /usr/include/sys

