/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKAnimation.h>

@interface LKAnimationGroup : LKAnimation
{
}

+ (unsigned long)copyPropertyList:(const struct _LKPropertyDescription **)fp8;	// IMP=0x30aea488
- (void *)LK_copyRenderValue;	// IMP=0x30aea4d8
- (id)animations;	// IMP=0x30aea67c
- (id)description;	// IMP=0x30aea5f4

@end

