/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKLayer.h>

@interface LKLayer (LKLayerScrolling)
- (void)_scrollPoint:(struct CGPoint)fp8 fromLayer:(id)fp16;	// IMP=0x30afa9cc
- (void)_scrollRect:(struct CGRect)fp8 fromLayer:(id)fp24;	// IMP=0x30afaa40
- (struct CGRect)_visibleRectOfLayer:(id)fp8;	// IMP=0x30afab04
- (void)scrollPoint:(struct CGPoint)fp8;	// IMP=0x30afaa18
- (void)scrollRectToVisible:(struct CGRect)fp8;	// IMP=0x30afaaac
- (struct CGRect)visibleRect;	// IMP=0x30afab84
@end

