/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>
#import <GraphicsServices/GraphicsServices.h>
#import <UIKit/UITextLabel.h>

@interface NSString (UIStringDrawing)

- (void)setStringDrawingOrigin:(CGPoint)stringDrawingOrigin;
- (void)clearStringDrawingOrigin;

- (CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(GSFontRef)font ellipsis:(UITextLabelEllipsisStyle)ellipsisStyle;
- (CGSize)drawAtPoint:(CGPoint)point withFont:(GSFontRef)font;
- (void)drawAtPoint:(CGPoint)point withStyle:(id)style;

- (CGSize)drawInRect:(CGRect)rect withFont:(GSFontRef)font;
- (CGSize)drawInRect:(CGRect)rect withFont:(GSFontRef)font ellipsis:(UITextLabelEllipsisStyle)ellipsisStyle;
- (CGSize)drawInRect:(CGRect)rect withFont:(GSFontRef)font ellipsis:(UITextLabelEllipsisStyle)ellipsisStyle alignment:(int)alignment; // enum needed
- (void)drawInRect:(CGRect)rect withStyle:(id)fp24;

- (void)drawMarkupAtPoint:(CGPoint)point;
- (void)drawMarkupInRect:(CGRect)rect;

- (CGSize)sizeInRect:(CGRect)rect withFont:(GSFontRef)font;
- (CGSize)sizeInRect:(CGRect)rect withFont:(GSFontRef)font ellipsis:(UITextLabelEllipsisStyle)ellipsisStyle;
- (CGSize)sizeWithFont:(GSFontRef)font;
- (CGSize)sizeWithFont:(GSFontRef)font forWidth:(float)width ellipsis:(UITextLabelEllipsisStyle)ellipsisStyle;
- (CGSize)sizeWithMarkupForWidth:(float)width;
- (CGSize)sizeWithStyle:(id)style forWidth:(float)width;

@end

