/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

typedef enum {
  kOrientationFlatUp = 0,
  kOrientationVertical = 1,
  kOrientationVerticalUpsideDown = 2,
  kOrientationHorizontalLeft = 3,
  kOrientationHorizontalRight = 4,
  kOrientationUnknown = 5,
  kOrientationFlatDown = 6
} UIHardwareOrientation;

@interface UIHardware : NSObject
{
}

+ (void)_setStatusBarHeight:(float)fp8;	// IMP=0x323e86e0
+ (UIHardwareOrientation)deviceOrientation:(BOOL)fp8;	// IMP=0x323e877c
+ (struct CGRect)fullScreenApplicationContentRect;	// IMP=0x323e8720
+ (BOOL)isTTYEnabled;	// IMP=0x323e8858
+ (struct CGSize)mainScreenSize;	// IMP=0x323e86f4
+ (int)ringerState;	// IMP=0x323e8750
+ (BOOL)setSpeakerPhoneEnabled:(BOOL)fp8;	// IMP=0x323e8808
+ (float)statusBarHeight;	// IMP=0x323e86d0

@end

