/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <GraphicsServices/GraphicsServices.h>
#import <UIKit/UIView.h>

typedef enum {
    kUITextLabelEllipsisNone = 0, // this shows how the ellipsis is
    kUITextLabelEllipsisLeading = 1, // this shows ... the ellipsis is added
	kUITextLabelEllipsisEnd = 2, // this shows how the ellipsis...
	kUITextLabelEllipsisTrailing = 3 // this shows how the ... is added
} UITextLabelEllipsisStyle;

@interface UITextLabel : UIView {}

+ (GSFontRef)defaultFont;

- (id)initWithFrame:(CGRect)frame;

- (void)drawContentsInRect:(CGRect)rect;
- (void)drawRect:(CGRect)rect;

- (void)sizeToFit;

- (CGColorRef)currentTextColor;
- (CGSize)textSize;
- (CGSize)ellipsizedTextSize;

- (BOOL)ignoresMouseEvents;

- (void)setEllipsisStyle:(UITextLabelEllipsisStyle)ellipsisStyle;

- (void)setEnabled:(BOOL)fp8;

- (BOOL)centersHorizontally;
- (void)setCentersHorizontally:(BOOL)centersHorizontally;

- (CGColorRef)color;
- (void)setColor:(CGColorRef)color;

- (GSFontRef)font;
- (void)setFont:(GSFontRef)font;

- (BOOL)isHighlighted;
- (void)setHighlighted:(BOOL)isHighlighted;

- (CGColorRef)highlightedColor;
- (void)setHighlightedColor:(CGColorRef)highlightedColor;	
	
- (id)text;
- (void)setText:(id)text;

- (BOOL)wrapsText;	
- (void)setWrapsText:(BOOL)wrapsText;	

- (CGColorRef)shadowColor;
- (void)setShadowColor:(CGColorRef)shadowColor;

- (CGSize)shadowOffset;
- (void)setShadowOffset:(CGSize)shadowOffset;

- (CGColorRef)_disabledFontColor;	
- (void)_invalidateTextSize;

@end
