/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <GraphicsServices/GraphicsServices.h>
#import <LayerKit/LKLayer.h>
#import <UIKit/UIResponder.h>

typedef enum {
	kUIViewSwipeUp = 1,
	kUIViewSwipeDown = 2,
	kUIViewSwipeLeft = 4,
	kUIViewSwipeRight = 8
} UIViewSwipeDirection;

@interface UIView : UIResponder {}

// class of backing LKLayer
+ (Class)layerClass;

// designated initializer
- (id)initWithFrame:(CGRect)frame;

// properties
- (float)charge;
- (void)setCharge:(float)fp8;

- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)fp8;

- (id)tapDelegate;
- (void)setTapDelegate:(id)fp8;

// swipes
- (BOOL)canHandleSwipes; // override in subclasses, defaults to YES in a table view
- (int)swipe:(UIViewSwipeDirection)swipeDirection withEvent:(GSEventRef)event;

// interface heartbeat callback
- (void)startHeartbeat:(SEL)heartbeatSelector inRunLoopMode:(NSString *)runloopMode;	
- (void)stopHeartbeat:(SEL)heartbeatSelector;

- (BOOL)cancelMouseTracking;

// private
- (unsigned int)_becomeFirstResponderWhenPossible;
- (void)_clearBecomeFirstResponderWhenCapable;
- (void)_createLayerWithFrame:(CGRect)frame;

@end

@interface UIView (Internal)
+ (BOOL)_invalidatesViewUponCreation;	
+ (void)_setInvalidatesViewUponCreation:(BOOL)fp8;	
+ (void)_setIsResponderAncestorOfFirstResponder:(BOOL)fp8 startingAtFirstResponder:(id)fp12;

// get the backing LKLayer
- (LKLayer *)_layer;

- (BOOL)_alwaysHandleInteractionEvents;	
- (BOOL)_alwaysHandleScrollerMouseEvent;	
- (BOOL)_canDrawContent;	
- (BOOL)_canHandleStatusBarMouseEvents;	
- (BOOL)_cancelTapDelegateTracking;	
- (BOOL)_containedInAbsoluteResponderChain;	
- (void)_didMoveFromWindow:(id)fp8 toWindow:(id)fp12;	
- (void)_didScroll;	
- (id)_interceptMouseEvent:(GSEventRef)fp8;	
- (void)_invalidateLayerContents;
- (void)_invalidateSubviewCache;
- (void)_mouseDown:(GSEventRef)fp8;
- (void)_mouseDragged:(GSEventRef)fp8;
- (void)_mouseUp:(GSEventRef)fp8;
- (void)_renderSnapshotWithRect:(CGRect)rect inContext:(CGContextRef)context;
- (id)_scroller;
- (void)_setContentImage:(id)fp8;
- (void)_setContentsTransform:(CGAffineTransform)transform;	
- (void)_setInterceptMouseEvent:(BOOL)fp8;
- (BOOL)_subclassImplementsDrawRect;
- (id)_window;
@end
