CC=arm-apple-darwin-cc
LD=$(CC)
CFLAGS=-Wall -ObjC
LDFLAGS=-F$(HEAVENLY)/System/Library/PrivateFrameworks -framework CoreFoundation -framework Foundation -framework vmutils -lobjc

all:	weaselprof

weaselprof:	weaselprof.o

