/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKBasicAnimation.h>

@interface LKBasicAnimation (LKBasicAnimationObsolete)
- (void)setFrom:(id)fp8;	// IMP=0x30af98cc
- (void)setTo:(id)fp8;	// IMP=0x30af98e8
@end

