/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKContext.h>

@interface LKContextImpl : LKContext
{
    struct _opaque_pthread_mutex_t _mutex;
    void *_next;
    void *_layer;
    struct _LKRenderContext *_renderCtx;
    unsigned int _serverPort;
    unsigned int _clientPort;
    unsigned int _clientId;
    unsigned int _localId;
    unsigned int _coderFlags;
    struct x_list_struct *_shmems;
    struct x_list_struct *_deletedShmems;
    float _level;
    unsigned int _fenceName;
    unsigned int _fenceCount;
    unsigned int _ownsServerPort:1;
    unsigned int _synchronized:1;
    unsigned int _serverDied:1;
}

- (unsigned int)_clientPort;	// IMP=0x30aeb6e0
- (unsigned int)contextId;	// IMP=0x30aeb924
- (unsigned int)createSlot;	// IMP=0x30aebb5c
- (void)dealloc;	// IMP=0x30aeb8c8
- (void)deleteSlot:(unsigned int)fp8;	// IMP=0x30aebbe4
- (id)initRemoteWithOptions:(id)fp8;	// IMP=0x30aeb730
- (id)initWithOptions:(id)fp8;	// IMP=0x30aeb5e4
- (void)invalidate;	// IMP=0x30aec664
- (id)layer;	// IMP=0x30aeb92c
- (float)level;	// IMP=0x30aebaec
- (void)orderAbove:(unsigned int)fp8;	// IMP=0x30aeba18
- (void)orderBelow:(unsigned int)fp8;	// IMP=0x30aeba34
- (struct _LKRenderContext *)renderContext;	// IMP=0x30aebaf4
- (void)setFence:(unsigned int)fp8 count:(unsigned int)fp12;	// IMP=0x30aebb10
- (void)setLayer:(id)fp8;	// IMP=0x30aeb934
- (void)setLevel:(float)fp8;	// IMP=0x30aeba50
- (void)setObject:(id)fp8 forSlot:(unsigned int)fp12;	// IMP=0x30aebc00
- (BOOL)valid;	// IMP=0x30aebafc

@end

