/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
#import <LayerKit/LKTimingFunction.h>

@interface LKAnimation : NSObject <NSCopying> {}

+ (id)animation;
+ (id)defaultValueForKey:(id)key;
+ (id)properties;
- (void)runActionForKey:(id)key object:(id)object arguments:(id)fp16;
- (BOOL)shouldArchiveValueForKey:(id)key;
- (void)setTimingFunction:(LKTimingFunction *)timingFunction;
- (void)setDuration:(float)duration;

@end

@interface LKAnimation (LKAnimationPrivate)
+ (void *)methodForSelector:(SEL)fp8;	// IMP=0x30ae9998
+ (BOOL)shouldCopyValueForKey:(id)fp8;	// IMP=0x30ae92c8
+ (BOOL)shouldRetainValueForKey:(id)fp8;	// IMP=0x30ae92b0
- (BOOL)autoreverses;	// IMP=0x30ae9a10
- (double)beginTime;	// IMP=0x30ae99e0
- (id)delegate;	// IMP=0x30ae9a30
- (double)duration;	// IMP=0x30ae99f0
- (id)fillMode;	// IMP=0x30ae9a18
- (double)frameInterval;	// IMP=0x30ae99d8
- (BOOL)removedOnCompletion;	// IMP=0x30ae9a20
- (float)repeatCount;	// IMP=0x30ae9a00
- (double)repeatDuration;	// IMP=0x30ae9a08
- (float)speed;	// IMP=0x30ae99f8
- (double)timeOffset;	// IMP=0x30ae99e8
- (id)timingFunction;	// IMP=0x30ae9a28
@end