/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKBasicAnimation.h>

@interface LKBasicAnimation (LKAnimationPrivate)
+ (unsigned long)copyPropertyList:(const struct _LKPropertyDescription **)fp8;	// IMP=0x30ae9da4
- (BOOL)roundsToInteger;	// IMP=0x30ae9df4
@end

