/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKPropertyAnimation.h>

@interface LKBasicAnimation : LKPropertyAnimation {}

- (id)byValue;
- (void)setByValue:(id)byValue;

- (id)fromValue;
- (void)setFromValue:(id)fromValue;

- (id)toValue;
- (void)setToValue:(id)toValue;

@end

@interface LKBasicAnimation (LKAnimationPrivate)

- (BOOL)roundsToInteger;

@end
