/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKPropertyAnimation.h>

@interface LKBasicAnimation : LKPropertyAnimation
{
}

- (id)byValue;	// IMP=0x30ae9d9c
- (id)fromValue;	// IMP=0x30ae9d8c
- (id)toValue;	// IMP=0x30ae9d94

@end

@interface LKBasicAnimation (LKAnimationPrivate)
- (BOOL)roundsToInteger;	// IMP=0x30ae9df4
@end
