/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKPropertyAnimation.h>

@interface LKKeyframeAnimation : LKPropertyAnimation {}

- (id)calculationMode;
- (void)setCalculationMode:(id)calculationMode;

- (NSArray *)keyTimes;
- (void)setKeyTimes:(NSArray *)keyTimes;

- (CGPathRef)path;
-(void)setPath:(CGPathRef)path;

- (NSArray *)timingFunctions;
- (void)setTimingFunctions:(NSArray *)timingFunctions;

- (NSArray *)values;
- (void)setValues:(NSArray *)values;

@end

