/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKPropertyAnimation.h>

@interface LKKeyframeAnimation : LKPropertyAnimation
{
}

- (void *)LK_copyRenderValue;	// IMP=0x30ae9e4c
- (id)calculationMode;	// IMP=0x30aea1c8
- (id)keyTimes;	// IMP=0x30aea1d0
- (struct CGPath *)path;	// IMP=0x30aea1e8
- (id)timingFunctions;	// IMP=0x30aea1d8
- (id)values;	// IMP=0x30aea1e0

@end

