/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKLayer.h>

#import "LKObjectPrivateProtocol.h"

@interface LKLayer (LKLayerPrivate) <LKObjectPrivate>
+ (unsigned long)copyPropertyList:(const struct _LKPropertyDescription **)fp8;	// IMP=0x30aeef68
+ (void *)methodForSelector:(SEL)fp8;	// IMP=0x30aef410
+ (BOOL)shouldCopyValueForKey:(id)fp8;	// IMP=0x30aef468
+ (BOOL)shouldRetainValueForKey:(id)fp8;	// IMP=0x30aef450
- (id)ancestorSharedWithLayer:(id)fp8;	// IMP=0x30af0de8
- (struct CGPoint)anchorPoint;	// IMP=0x30aef4c0
- (BOOL)autoreverses;	// IMP=0x30aef4b0
- (struct CGColor *)backgroundColor;	// IMP=0x30aef61c
- (id)backgroundFilters;	// IMP=0x30aef634
- (double)beginTime;	// IMP=0x30aef480
- (id)compositingFilter;	// IMP=0x30aef63c
- (struct CGAffineTransform)contentsTransform;	// IMP=0x30aef5b8
- (void)displayIfNeeded;	// IMP=0x30aef008
- (double)duration;	// IMP=0x30aef490
- (id)fillMode;	// IMP=0x30aef4b8
- (id)filters;	// IMP=0x30aef62c
- (id)hitTest:(struct CGPoint)fp8 options:(unsigned int)fp16;	// IMP=0x30af0ea8
- (void)invalidateContents;	// IMP=0x30af0888
- (BOOL)isDescendantOf:(id)fp8;	// IMP=0x30af0e68
- (id)magnificationFilter;	// IMP=0x30aef604
- (id)minificationFilter;	// IMP=0x30aef60c
- (id)name;	// IMP=0x30aef624
- (float)nearClippingDepth;	// IMP=0x30aef4f8
- (BOOL)needsDisplay;	// IMP=0x30aeeff8
- (BOOL)needsLayout;	// IMP=0x30aef030
- (float)opacity;	// IMP=0x30aef614
- (void *)regionBeingDrawn;	// IMP=0x30aeefb8
- (float)repeatCount;	// IMP=0x30aef4a0
- (double)repeatDuration;	// IMP=0x30aef4a8
- (void)setContentsChanged;	// IMP=0x30af0870
- (struct CGSize)size;	// IMP=0x30aef090
- (float)speed;	// IMP=0x30aef498
- (id)sublayerEnumerator;	// IMP=0x30aef040
- (struct LKTransform)sublayerTransform;	// IMP=0x30aef55c
- (double)timeOffset;	// IMP=0x30aef488
- (struct LKTransform)transform;	// IMP=0x30aef500
- (float)zPosition;	// IMP=0x30aef4f0
@end

