/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKAnimation.h>

@interface LKPropertyAnimation : LKAnimation
{
}

+ (id)animationWithKeyPath:(id)fp8;	// IMP=0x30ae9a88
- (BOOL)additive;	// IMP=0x30ae9c1c
- (BOOL)cumulative;	// IMP=0x30ae9c2c
- (id)description;	// IMP=0x30ae9b94
- (id)keyPath;	// IMP=0x30ae9c24

@end

