/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKLayer.h>

@interface LKScrollLayer : LKLayer
{
}

+ (id)defaultValueForKey:(id)fp8;	// IMP=0x30afa524
- (void)_scrollPoint:(struct CGPoint)fp8 fromLayer:(id)fp16;	// IMP=0x30afa7f8
- (void)_scrollRect:(struct CGRect)fp8 fromLayer:(id)fp24;	// IMP=0x30afa85c
- (struct CGRect)_visibleRectOfLayer:(id)fp8;	// IMP=0x30afa8f4
- (void)scrollToPoint:(struct CGPoint)fp8;	// IMP=0x30afa5b0
- (void)scrollToRect:(struct CGRect)fp8;	// IMP=0x30afa670

@end

