/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKTransition.h>

@interface LKTransition (LKTransitionPrivate)
- (unsigned int)transitionFlags;	// IMP=0x30aea480
@end

