/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSValue.h"

@interface NSValue (LKTransformAdditions)
+ (id)valueWithLKTransform:(struct LKTransform)fp8;	// IMP=0x30af5aa8
- (struct LKTransform)LKTransformValue;	// IMP=0x30af5ae8
@end

