/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKAnimation.h>

@interface LKAnimation (LKAnimationObsolete)
- (void)setBegin:(double)fp8;	// IMP=0x30af9858
- (void)setFill:(BOOL)fp8;	// IMP=0x30af9890
- (void)setOffset:(double)fp8;	// IMP=0x30af9874
@end

