/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKLayer.h>

@interface LKLayer (_LKLayerObsolete)
+ (id)defaultActionForKeyPath:(id)fp8;	// IMP=0x30af9a08
- (id)actionForKeyPath:(id)fp8;	// IMP=0x30af9a24
- (id)contentsFilterMode;	// IMP=0x30af99b4
- (void)invalidateLayout;	// IMP=0x30af99d0
- (void)removeAnimationsForKey:(id)fp8;	// IMP=0x30af99ec
- (void)setBegin:(double)fp8;	// IMP=0x30af9904
- (void)setContentsFilterMode:(id)fp8;	// IMP=0x30af9978
- (void)setFill:(BOOL)fp8;	// IMP=0x30af993c
- (void)setOffset:(double)fp8;	// IMP=0x30af9920
@end

