/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <LayerKit/LKLayer.h>

@interface LKLayer (LKLayerRender)
- (void *)LK_copyRenderValue;	// IMP=0x30af30d0
@end

