/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface LKSlotProxy : NSObject
{
    struct _LKRenderProxy *_proxy;
}

- (void *)LK_copyRenderValue;	// IMP=0x30aebf0c
- (void)dealloc;	// IMP=0x30aebec0
- (id)initWithName:(unsigned int)fp8;	// IMP=0x30aebe38

@end

