/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSAffineTransform.h"

@interface NSAffineTransform (LKRenderValue)
- (void *)LK_copyRenderValue;	// IMP=0x30afa2d8
@end

