/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface UIAnimation : NSObject
{
    id _target;
    SEL _action;
    id _delegate;
    struct {
        unsigned int curve:4;
        unsigned int tvOutput:1;
        unsigned int reserved:27;
    } _animationFlags;
    double _startTime;
    double _duration;
    int _state;
}

- (SEL)action;	// IMP=0x323fc8e4
- (void)dealloc;	// IMP=0x323fca38
- (id)delegate;	// IMP=0x323fc8d4
- (id)initWithTarget:(id)fp8;	// IMP=0x323fc794
- (float)progressForFraction:(float)fp8;	// IMP=0x323fc908
- (void)setAction:(SEL)fp8;	// IMP=0x323fc8dc
- (void)setAnimationCurve:(int)fp8;	// IMP=0x323fc8ec
- (void)setDelegate:(id)fp8;	// IMP=0x323fc8cc
- (void)setProgress:(float)fp8;	// IMP=0x323fc904
- (void)stopAnimation;	// IMP=0x323fc884
- (id)target;	// IMP=0x323fc8c4

@end

