/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIAnimation (Internal)
- (float)fractionForTime:(double)fp8;	// IMP=0x323fcac8
- (void)markStart:(double)fp8;	// IMP=0x323fcb5c
- (void)markStop;	// IMP=0x323fcb70
- (void)setDuration:(double)fp8;	// IMP=0x323fcab4
- (int)state;	// IMP=0x323fca9c
- (BOOL)tvOutput;	// IMP=0x323fcaa4
@end

